import type { TokenRecord } from '@sentinel/shared';
import { ExternalLink, RefreshCw, X, Copy, CheckCircle2, AlertTriangle } from 'lucide-react';
import { useState } from 'react';
import { RiskBadge } from './RiskBadge';
import { rescan } from '../lib/api';
import { dexScreenerUrl, openSeaUrl } from '../lib/externalLinks';
const fmt=(v:number|null)=>v==null?'Unknown':`${v.toFixed(2)}%`;
const money=(v:number|null)=>v==null?'Unknown':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
export function TokenDrawer({token,onClose}:{token:TokenRecord|null;onClose:()=>void}){
 const [copied,setCopied]=useState(false); const [refreshing,setRefreshing]=useState(false); if(!token)return null;
 const copy=()=>{navigator.clipboard.writeText(token.address);setCopied(true);setTimeout(()=>setCopied(false),1000)};
 const refresh=async()=>{setRefreshing(true);try{await rescan(token.chainKey,token.address);setTimeout(()=>setRefreshing(false),2500);}catch{setRefreshing(false);}};
 return <div className="overlay" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="icon close" onClick={onClose}><X/></button>
  <div className="drawer-head"><div className="eyebrow">{token.chainName.toUpperCase()} / {token.assetType==='ERC721'?'NFT COLLECTION':'TOKEN'} ANALYSIS</div><h2>{token.name||'Unknown'} <span>${token.symbol||'???'}</span></h2><button className="address" onClick={copy}>{token.address}<Copy size={14}/>{copied&&<em>copied</em>}</button><div className="big-risk"><RiskBadge label={token.riskLabel} score={token.riskScore}/></div></div>
  <section className="metrics"><div><label>Contract type</label><strong>{token.assetType}</strong></div>{token.assetType==='ERC721'?<><div><label>Total minted</label><strong>{token.totalSupply??'Unknown'}</strong></div></>:<><div><label>Market cap</label><strong>{money(token.marketCapUsd)}</strong></div><div><label>Liquidity</label><strong>{money(token.liquidityUsd)}</strong></div><div><label>Holders</label><strong>{token.holderCountEstimate??'—'}</strong></div><div><label>Top 5 raw</label><strong>{fmt(token.top5Percent)}</strong></div><div><label>Top 5 circulating</label><strong>{fmt(token.circulatingTop5Percent)}</strong></div><div><label>Buy tax</label><strong>{fmt(token.buyTax)}</strong></div><div><label>Sell tax</label><strong>{fmt(token.sellTax)}</strong></div><div><label>LP created</label><strong>{token.poolCreated?'YES':'NO'}</strong></div></>}<div><label>Source verified</label><strong>{token.verified===true?'YES':token.verified===false?'NO':'UNKNOWN'}</strong></div><div><label>Owner</label><strong className="mono small">{token.owner?`${token.owner.slice(0,8)}…${token.owner.slice(-5)}`:'Unknown'}</strong></div></section>
  <section><div className="section-title">Warnings <span>{token.warnings.length}</span></div>{token.warnings.length?<div className="warning-list">{token.warnings.map(w=><article className={`warning ${w.severity}`} key={w.code}><AlertTriangle size={18}/><div><b>{w.title}</b><p>{w.detail}</p>{w.evidence&&<code>{w.evidence}</code>}</div></article>)}</div>:<div className="clear-card"><CheckCircle2/> No detected warnings. This is not a guarantee that the contract is safe.</div>}</section>
  {token.assetType==='ERC20'&&token.pools.length>0&&<section><div className="section-title">Liquidity pools <span>{token.pools.length}</span></div>{token.pools.map(p=><a className="pool" key={p.address} href={`${token.explorerUrl}/address/${p.address}`} target="_blank"><span>{p.protocol.toUpperCase()}</span><code>{p.address}</code>{p.fee!=null&&<i>fee {p.fee}</i>}<ExternalLink size={15}/></a>)}</section>}
  {token.assetType==='ERC20'&&token.topHolders.length>0&&<section><div className="section-title">Top reconstructed holders</div>{token.topHolders.map((h,i)=><div className="holder" key={h.address}><span>#{i+1}</span><a href={`${token.explorerUrl}/address/${h.address}`} target="_blank">{h.address.slice(0,10)}…{h.address.slice(-6)}</a><b>{h.percent.toFixed(2)}%</b>{h.excluded&&<em>{h.label||'excluded'}</em>}</div>)}</section>}
  <div className="drawer-actions"><a href={`${token.explorerUrl}/address/${token.address}`} target="_blank" rel="noreferrer">Explorer <ExternalLink size={15}/></a><a href={token.assetType==='ERC20'?dexScreenerUrl(token.address):openSeaUrl(token.chainKey,token.address)} target="_blank" rel="noreferrer">{token.assetType==='ERC20'?'DexScreener':'OpenSea'} <ExternalLink size={15}/></a><button disabled={refreshing} onClick={refresh}><RefreshCw className={refreshing?'spin':''} size={15}/> {refreshing?'Refresh queued':'Rescan now'}</button></div>
 </aside></div>;
}
